# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ApplyStyle
                                 A QGIS plugin
 The plugin applys the style of the selected vector layer (like label, symbol...)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-22
        copyright            : (C) 2025 by sjbang
        email                : sjbang@spacen.or.kr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ApplyStyle class from file ApplyStyle.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .apply_style import ApplyStyle
    return ApplyStyle(iface)
