# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ApplyStyle
                                 A QGIS plugin
 The plugin applys the style of the selected vector layer (like label, symbol...)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-09-22
        git sha              : $Format:%H$
        copyright            : (C) 2025 by sjbang
        email                : sjbang@spacen.or.kr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from fileinput import filename
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import QgsProject, Qgis, QgsWkbTypes, QgsTextFormat, QgsTextBufferSettings, QgsPalLayerSettings, QgsVectorLayerSimpleLabeling
from PyQt5.QtGui import QColor, QFont
from qgis.utils import iface

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .apply_style_dialog import ApplyStyleDialog
import os.path


class ApplyStyle:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ApplyStyle_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Apply Style')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ApplyStyle', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/apply_style/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Apply Style'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Apply Style'),
                action)
            self.iface.removeToolBarIcon(action)

    def editSymbol(self, layer_name):
        input_layers = QgsProject.instance().mapLayersByName(layer_name)
        layer = input_layers[0]

        # layer = iface.activeLayer()

        if layer is None:
            print("활성화된 레이어가 없습니다. 변경할 레이어를 선택해주세요.")
        else:
            # 2. 심볼 라인 너비 설정
            # target_line_width = 2.0 # <--- 여기에 원하는 라인 너비를 입력하세요.
            target_line_width = float(self.dlg.lineEdit.text())

            renderer = layer.renderer()
            geom_type = layer.wkbType() # 레이어의 기하학적 타입 가져오기

            # 레이어가 라인 또는 폴리곤 타입인지 확인 (QgsWkbTypes 상수를 직접 비교)
            if (geom_type == QgsWkbTypes.LineString or
                geom_type == QgsWkbTypes.MultiLineString or
                geom_type == QgsWkbTypes.Polygon or
                geom_type == QgsWkbTypes.MultiPolygon):

                if renderer is not None and renderer.symbol() is not None:
                    symbol = renderer.symbol()
                    line_symbols_found = 0
                    
                    # 심볼의 각 레이어를 순회하며 라인 심볼을 찾아서 너비 변경
                    for sym_layer in symbol.symbolLayers():
                        # 라인 심볼 레이어인지 확인 (width 속성을 가지며 마커 심볼이 아님)
                        if hasattr(sym_layer, 'width') and sym_layer.type() != 'SimpleMarker':
                            sym_layer.setWidth(target_line_width)
                            line_symbols_found += 1
                            
                    if line_symbols_found > 0:
                        layer.triggerRepaint() # 레이어 다시 그리기 (변경사항 적용)
                        # print(f"'{layer.name()}' 레이어 심볼의 라인 너비를 {target_line_width}으로 설정했습니다. (총 {line_symbols_found}개 라인 심볼 레이어 변경)")
                        self.iface.messageBar().pushMessage(f"'{layer.name()}' 레이어 심볼의 라인 너비를 {target_line_width}으로 설정했습니다. (총 {line_symbols_found}개 라인 심볼 레이어 변경)",level=Qgis.Success, duration=3)
                    else:
                        # print(f"'{layer.name()}' 레이어 심볼에서 설정 가능한 라인 심볼 레이어를 찾을 수 없습니다. (포인트 심볼 제외)")
                        self.iface.messageBar().pushMessage(f"'{layer.name()}' 레이어 심볼에서 설정 가능한 라인 심볼 레이어를 찾을 수 없습니다. (포인트 심볼 제외)",level=Qgis.Warning, duration=3)
                else:
                    # print(f"'{layer.name()}' 레이어에 렌더러나 심볼이 설정되어 있지 않습니다.")
                    self.iface.messageBar().pushMessage(f"'{layer.name()}' 레이어에 렌더러나 심볼이 설정되어 있지 않습니다.",level=Qgis.Warning, duration=3)
            else:
                # print(f"'{layer.name()}'은(는) 선 또는 폴리곤 레이어가 아닙니다. 라인 심볼 너비를 변경할 수 없습니다.")
                self.iface.messageBar().pushMessage(f"'{layer.name()}'은(는) 선 또는 폴리곤 레이어가 아닙니다. 라인 심볼 너비를 변경할 수 없습니다.",level=Qgis.Warning, duration=3)

    def get_layer_field_names(self, layer):

        field_names = []
        # 레이어의 필드 객체들을 가져옵니다.
        fields = layer.fields()
        for field in fields:
            # 각 필드의 이름을 리스트에 추가합니다.
            field_names.append(field.name())
        
        self.dlg.comboBox.clear()
        self.dlg.comboBox.addItems([field_names[i] for i in range(len(field_names))])

    def set_layer_labeling(self, layer_name):

        input_layers = QgsProject.instance().mapLayersByName(layer_name)
        layer = input_layers[0]

        fontSize = self.dlg.lineEdit_2.text()
        fontColor = self.dlg.lineEdit_3.text()
        label_field_name = self.dlg.comboBox.currentText()

        text_format = QgsTextFormat()
        text_format.setFont(QFont("Arial"))
        text_format.setSize(int(fontSize))
        text_format.setColor(QColor(fontColor))
        buffer_settings = QgsTextBufferSettings()
        buffer_settings.setEnabled(True)
        buffer_settings.setSize(1)
        buffer_settings.setColor(QColor("gray"))
        text_format.setBuffer(buffer_settings)
        layer_settings = QgsPalLayerSettings()
        layer_settings.setFormat(text_format)
        layer_settings.fieldName = label_field_name
        layer_settings.placement = QgsPalLayerSettings.Line
        label_settings = QgsVectorLayerSimpleLabeling(layer_settings)
        layer.setLabelsEnabled(True)
        layer.setLabeling(label_settings)
        layer.triggerRepaint()

        # print(f"'{layer_name}' 레이어의 라벨이 '{label_field_name}' 필드로 설정되었습니다.")
        # print("라벨링이 성공적으로 적용되었습니다!")
        self.iface.messageBar().pushMessage(f"'{layer_name}' 레이어의 라벨이 '{label_field_name}' 필드로 설정되었습니다.",level=Qgis.Success, duration=3)
        self.iface.messageBar().pushMessage("라벨링이 성공적으로 적용되었습니다!",level=Qgis.Success, duration=3)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ApplyStyleDialog()
            # tab1(line width)
            self.dlg.lineEdit.setText("2.0")  # 기본값 설정
            self.dlg.listWidget.addItems([layer.name() for layer in QgsProject.instance().mapLayers().values()])
            self.dlg.pushButton.clicked.connect(lambda: self.editSymbol(self.dlg.listWidget.currentItem().text()))
            # tab2(label)
            self.dlg.listWidget_2.addItems([layer.name() for layer in QgsProject.instance().mapLayers().values()])
            self.dlg.listWidget_2.currentItemChanged.connect(lambda: self.get_layer_field_names(QgsProject.instance().mapLayersByName(self.dlg.listWidget_2.currentItem().text())[0]))
            self.dlg.lineEdit_2.setText("12")  # font size 기본값 설정
            self.dlg.lineEdit_3.setText("black")  # font color 기본값
            self.dlg.pushButton_3.clicked.connect(lambda: self.set_layer_labeling(self.dlg.listWidget_2.currentItem().text()))
            # 닫기버튼
            self.dlg.pushButton_2.clicked.connect(self.dlg.close)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass


