# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LinkSyncFlasher
                                 A QGIS plugin
 Automatically synchronizes and flashes related features across multiple layers based on attribute ID matching.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-09
        copyright            : (C) 2026 by SPACEN
        email                : sj.bang@spacen.or.kr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LinkSyncFlasher class from file LinkSyncFlasher.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .link_sync_flasher import LinkSyncFlasher
    return LinkSyncFlasher(iface)
