# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LinkSyncFlasher
                                 A QGIS plugin
 Automatically synchronizes and flashes related features across multiple layers based on attribute ID matching.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-09
        git sha              : $Format:%H$
        copyright            : (C) 2026 by SPACEN
        email                : sj.bang@spacen.or.kr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon, QColor
from qgis.PyQt.QtWidgets import QAction
from qgis.utils import iface
from qgis.core import QgsProject, NULL
from qgis.gui import QgsMapToolIdentify, QgsRubberBand
from qgis.core import QgsProject, QgsVectorLayer, QgsRectangle, QgsWkbTypes, QgsApplication
from PyQt5.QtWidgets import QAction, QShortcut
from PyQt5.QtGui import QIcon, QColor, QKeySequence
from PyQt5.QtCore import Qt, QObject

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .link_sync_flasher_dialog import LinkSyncFlasherDialog
import os.path

class MagicDragSelectTool(QgsMapToolIdentify):
    def __init__(self, canvas):
        super().__init__(canvas)
        self.canvas = canvas
        self.dragging = False
        self.rubber_band = QgsRubberBand(self.canvas, QgsWkbTypes.PolygonGeometry)
        self.rubber_band.setColor(QColor(0, 120, 215, 60)) 
        self.rubber_band.setWidth(1)
        self.setCursor(Qt.PointingHandCursor)

    def canvasPressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.dragging = True
            self.start_pos = event.pos()
            self.rubber_band.reset(QgsWkbTypes.PolygonGeometry)

    def canvasMoveEvent(self, event):
        if self.dragging:
            rect = QgsRectangle(self.toMapCoordinates(self.start_pos), self.toMapCoordinates(event.pos()))
            self.rubber_band.setToCanvasRectangle(self.canvas.mapSettings().mapToPixel().transform(rect).toRect())
            self.rubber_band.show()

    def canvasReleaseEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.dragging = False
            self.rubber_band.hide()
            end_pos = event.pos()
            
            if (self.start_pos - end_pos).manhattanLength() < 5:
                results = self.identify(event.x(), event.y(), self.TopDownAll)
            else:
                rect = QgsRectangle(self.toMapCoordinates(self.start_pos), self.toMapCoordinates(end_pos))
                results = self.identify(rect, self.TopDownAll)

            if not results: return

            target_res = results[0]
            layer = target_res.mLayer
            if isinstance(layer, QgsVectorLayer):
                if iface.activeLayer() != layer:
                    iface.layerTreeView().setCurrentLayer(layer)
                
                layer.removeSelection()
                if (self.start_pos - end_pos).manhattanLength() < 5:
                    layer.select(target_res.mFeature.id())
                else:
                    ids = [res.mFeature.id() for res in results if res.mLayer == layer]
                    layer.selectByIds(ids)
                
                self.canvas.refresh()
                iface.statusBarIface().showMessage(f"✨ {layer.name()} 선택됨", 1000)


class LinkSyncFlasher:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'LinkSyncFlasher_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&LinkSyncFlasher')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('LinkSyncFlasher', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/link_sync_flasher/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Link Selection Sync and Flash'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&LinkSyncFlasher'),
                action)
            self.iface.removeToolBarIcon(action)


    def clean_val(self, v):
        """데이터 타입을 무시하고 비교 가능한 깨끗한 문자열로 변환"""
        if v is None or v == NULL: return None
        try:
            # 소수점 제거 (100.0 -> 100) 후 문자열 변환
            return str(int(float(v))).strip()
        except:
            return str(v).strip()

    def sync_and_flash_rs1_fix(self, SRC_LAYER_NAME, SRC_KEY_FIELD, TARGET_CONFIG):
        """현재 활성화된 탭의 설정에 따라 레이어 동기화 및 플래싱 수행"""

        try:
            layers = QgsProject.instance().mapLayersByName(SRC_LAYER_NAME)
            if not layers:
                print(f"Error: {SRC_LAYER_NAME} 레이어를 찾을 수 없습니다.")
                return
            src_layer = layers[0]
            
            src_key_idx = src_layer.fields().lookupField(SRC_KEY_FIELD)
            if src_key_idx < 0:
                print(f"Error: {SRC_LAYER_NAME} 레이어에 {SRC_KEY_FIELD} 필드가 없습니다.")
                return

            selected_keys = {self.clean_val(f[src_key_idx]) for f in src_layer.selectedFeatures() if f[src_key_idx] is not None}
            # None 또는 빈 문자열 제거
            selected_keys.discard(None)
            selected_keys.discard('')
            
            if not selected_keys: 
                # print("알림: 선택된 피처가 없거나 키 값이 비어있습니다.")
                return

            for target_name, field_settings in TARGET_CONFIG.items():
                if not target_name: continue
                t_layers = QgsProject.instance().mapLayersByName(target_name)
                if not t_layers: continue
                tgt_layer = t_layers[0]
                
                # 레이어 가시성 확인 (꺼져있으면 Flash 안 보임)
                if not QgsProject.instance().layerTreeRoot().findLayer(tgt_layer.id()).isVisible():
                    # print(f"알림: {target_name} 레이어가 꺼져 있어 Flash가 보이지 않을 수 있습니다.")
                    pass

                color_groups = {}
                for f in tgt_layer.getFeatures():
                    for field_name, color_hex in field_settings.items():
                        # 필드 존재 여부 확인 (대소문자 무시 검색)
                        idx = f.fields().lookupField(field_name)
                        if idx < 0: continue
                        
                        val = self.clean_val(f[idx])
                        if val in selected_keys:
                            if color_hex not in color_groups: color_groups[color_hex] = []
                            color_groups[color_hex].append(f.id())
                            break

                for color_hex, ids in color_groups.items():
                    if ids:
                        color = QColor(color_hex)
                        end_color = QColor(color.red(), color.green(), color.blue(), 0)
                        self.iface.mapCanvas().flashFeatureIds(tgt_layer, ids, color, end_color, 3, 300)
                        
        except Exception as e:
            print(f"Error in sync_and_flash_rs1_fix: {e}")

    def initiate_sync(self):
        """연결 초기화 및 재연결을 수행합니다."""
        tab_index = self.dlg.tabWidget.currentIndex()
        # if tab_index == 0:
        #     SRC_LAYER_NAME = self.dlg.lineEdit.text()
        # else:
        #     SRC_LAYER_NAME = self.dlg.lineEdit_11.text()

        if tab_index == 0:  # Tab 1: L_link R_link Sync
            SRC_LAYER_NAME = self.dlg.lineEdit.text()
            SRC_KEY_FIELD = self.dlg.lineEdit_2.text()
            TARGET_CONFIG = {
                self.dlg.lineEdit_3.text(): {'L_linkID': self.dlg.lineEdit_6.text()},
                self.dlg.lineEdit_4.text(): {'L_linkID': self.dlg.lineEdit_7.text(), 'R_linkID': self.dlg.lineEdit_10.text()},
                self.dlg.lineEdit_5.text(): {'L_linkID': self.dlg.lineEdit_8.text()}
            }
        else:  # Tab 2: PW ID Sync (index 1)
            SRC_LAYER_NAME = self.dlg.lineEdit_11.text()
            SRC_KEY_FIELD = self.dlg.lineEdit_12.text()
            TARGET_CONFIG = {
                self.dlg.lineEdit_13.text(): {'PathwayID': self.dlg.lineEdit_14.text()},
            }

        try:
            layers = QgsProject.instance().mapLayersByName(SRC_LAYER_NAME)
            if not layers:
                print(f"Error: {SRC_LAYER_NAME} 레이어를 찾을 수 없습니다.")
                return
            src_obj = layers[0]

            # 연결 초기화 (기존 슬롯 연결 해제)
            try:
                src_obj.selectionChanged.disconnect()
            except:
                pass

            # 재연결
            src_obj.selectionChanged.connect(lambda *args: self.sync_and_flash_rs1_fix(SRC_LAYER_NAME, SRC_KEY_FIELD, TARGET_CONFIG))
            print(f"{SRC_LAYER_NAME} 레이어의 selectionChanged 이벤트가 연결되었습니다. 코드 실행 중...")
            
            # 연결 즉시 현재 선택 상태에 대해 1회 실행
            self.sync_and_flash_rs1_fix(SRC_LAYER_NAME, SRC_KEY_FIELD, TARGET_CONFIG)
            
        except Exception as e:
            print(f"Error in initiate_sync: {e}")

    # 만능 드래그 선택
    def setup_final_magic_tool(self):
        # 중복 제거 (기존 액션 및 단축키 청소)
        if hasattr(iface, 'magic_action'):
            iface.removeToolBarIcon(iface.magic_action)
        
        # 새로운 액션 생성
        icon = QIcon(QgsApplication.iconPath("mActionStar.svg"))
        action = QAction(icon, "만능 드래그 선택 (End)", iface.mainWindow())
        action.setCheckable(True)
        action.setObjectName("MagicSelectAction") # 시스템 내부 이름 설정
        
        def toggle_tool():
            canvas = iface.mapCanvas()
            if action.isChecked():
                iface.magic_tool = MagicDragSelectTool(canvas)
                canvas.setMapTool(iface.magic_tool)
                iface.statusBarIface().showMessage("🌟 만능 선택 모드 활성화", 2000)
            else:
                canvas.unsetMapTool(getattr(iface, 'magic_tool', None))
                iface.statusBarIface().showMessage("만능 선택 모드 해제", 1000)

        action.triggered.connect(toggle_tool)
        
        # 툴 변경 시 버튼 상태 동기화
        iface.mapCanvas().mapToolSet.connect(lambda tool: action.setChecked(tool == getattr(iface, 'magic_tool', None)))

        # 툴바에 추가
        iface.addToolBarIcon(action)
        iface.magic_action = action

        # --- 3. [핵심] End 키 단축키 강제 연결 ---
        # QAction에 단축키 직접 할당 (가장 우선순위가 높음)
        action.setShortcut(QKeySequence(Qt.Key_End))
        
        # QGIS 단축키 매니저에 등록 (설정 -> 키보드 단축키에 나타나게 함)
        iface.registerMainWindowAction(action, "End")

        print("✅ [최종 완료] 이제 'End' 키로 기능을 켜고 끌 수 있습니다.")
        print("💡 만약 작동하지 않으면 QGIS 상단의 별표 아이콘을 직접 확인해보세요.")

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = LinkSyncFlasherDialog()
            # 만능 드래그 선택
            self.dlg.pushButton_4.clicked.connect(self.setup_final_magic_tool)

            # tab1
            self.dlg.lineEdit.setText("NT2_LINK")  # 기본값 설정
            self.dlg.lineEdit_2.setText("ID")  # 기본값 설정
            self.dlg.lineEdit_3.setText("RS1_ROADBORDER")  # 기본값 설정
            self.dlg.lineEdit_4.setText("RM1_LANELINE")  # 기본값 설정
            self.dlg.lineEdit_5.setText("SF1_BARRIER")  # 기본값 설정
            self.dlg.lineEdit_6.setText("#FF0000")  # 기본값 설정
            self.dlg.lineEdit_7.setText("#FF0000")  # 기본값 설정
            self.dlg.lineEdit_8.setText("#FF0000")  # 기본값 설정
            self.dlg.lineEdit_9.setText("RM1_LANELINE")  # 기본값 설정
            self.dlg.lineEdit_10.setText("#0000FF")  # 기본값 설정

            # tab2
            self.dlg.lineEdit_11.setText("PW1_PATHWAY")  # 기본값 설정
            self.dlg.lineEdit_12.setText("ID")  # 기본값 설정
            self.dlg.lineEdit_13.setText("RS1_ROADBORDER")  # 기본값 설정
            self.dlg.lineEdit_14.setText("#00FF00")  # 기본값 설정  

            # 실행버튼: initiate_sync를 연결하여 자동 동기화 시작
            self.dlg.pushButton_2.clicked.connect(self.initiate_sync)
            self.dlg.pushButton_3.clicked.connect(self.initiate_sync)

            # 닫기버튼
            self.dlg.pushButton.clicked.connect(self.dlg.close)



        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
