# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ExportGeoquery
                                 A QGIS plugin
 This plugin save the attributes of the selected vector layer filtering by geoquery.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-23
        copyright            : (C) 2025 by spacen
        email                : sj.bang@spacen.or.kr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ExportGeoquery class from file ExportGeoquery.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .export_geoquery import ExportGeoquery
    return ExportGeoquery(iface)
