# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ExportGeoquery
                                 A QGIS plugin
 This plugin save the attributes of the selected vector layer filtering by geoquery.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-09-23
        git sha              : $Format:%H$
        copyright            : (C) 2025 by spacen
        email                : sj.bang@spacen.or.kr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import QgsProject, Qgis, QgsVectorFileWriter,  QgsFeatureRequest

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .export_geoquery_dialog import ExportGeoqueryDialog
import os.path


class ExportGeoquery:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ExportGeoquery_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Export Geoquery')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ExportGeoquery', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/export_geoquery/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Save Attributes Filtering by Geoquery'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Export Geoquery'),
                action)
            self.iface.removeToolBarIcon(action)

    def select_output_file(self):
        filename, _filter = QFileDialog.getSaveFileName(
            self.dlg, "Select output file", "", '*.shp')
        self.dlg.lineEdit_2.setText(filename)

    def export_selected_features(self):

        layers = QgsProject.instance().layerTreeRoot().children()

        selectedLayerIndex = self.dlg.comboBox.currentIndex()
        selectedLayer = layers[selectedLayerIndex].layer()
        expression = self.dlg.lineEdit.text()
        output_filepath = self.dlg.lineEdit_2.text()

        layer_name = selectedLayer.name()
        input_layers = QgsProject.instance().mapLayersByName(layer_name)
        layer = input_layers[0]

        layer.selectByExpression(expression)
        
        output_format = "ESRI Shapefile" # "ESRI Shapefile", "GPKG", "GeoJSON" 등 원하는 형식
        # output_filepath = os.path.join(output_dir, output_filename)
        # os.makedirs(output_dir, exist_ok=True) # 출력 디렉토리 생성

        # QgsVectorFileWriter를 사용하여 선택된 피처만 파일로 내보내기
        # 'onlySelected=True'가 핵심입니다!
        QgsVectorFileWriter.writeAsVectorFormat(
            layer,
            output_filepath,
            'korean',
            driverName='ESRI Shapefile',
            onlySelected=True
        )

        # print(f"쿼리로 선택된 피처가 '{output_filepath}' (으)로 성공적으로 내보내졌습니다.")
        self.iface.messageBar().pushMessage(
                f"쿼리로 선택된 피처가 '{output_filepath}' (으)로 성공적으로 내보내졌습니다.",
                level=Qgis.Success, duration=3)

        # 내보낸 레이어를 QGIS에 추가 (선택 사항)
        self.iface.addVectorLayer(output_filepath, os.path.basename(output_filepath), 'ogr')

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ExportGeoqueryDialog()
            self.dlg.pushButton.clicked.connect(self.select_output_file)
            self.dlg.pushButton_2.clicked.connect(self.export_selected_features)
            self.dlg.pushButton_3.clicked.connect(self.dlg.close)

        # Fetch the currently loaded layers
        layers = QgsProject.instance().layerTreeRoot().children()
        # Clear the contents of the comboBox from previous runs
        self.dlg.comboBox.clear()
        # Populate the comboBox with names of all the loaded layers
        self.dlg.comboBox.addItems([layer.name() for layer in layers])
        

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.

            pass
